name: Update Holidays CSV

on:
  schedule:
    - cron: '0 0 1 * *'  # 毎月1日の00:00に実行
  workflow_dispatch:  # 手動実行用

jobs:
  update-csv:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests

    - name: Run CSV filter script
      run: python code/get_holiday.py

    - name: Commit and push if changed
      run: |
        git config --global user.name 'GitHub Actions'
        git config --global user.email 'actions@github.com'
        git add holiday_data/filtered_holidays.csv
        git diff --quiet && git diff --staged --quiet || (git commit -m "Update filtered holidays CSV"; git push)
